service: echobot

provider:
  name: aws
  runtime: nodejs6.10
  region: ap-northeast-1
  profile: aldy120
  environment:
    CLIENT_ID: ${file(local.yml):slack.clientId}
    CLIENT_SECRET: ${file(local.yml):slack.clientSecret}
    ACCESS_TOKEN: ${file(local.yml):slack.accessToken}

functions:
  event:
    handler: handler.event
    events: 
      - http:
          path: event
          method: get
      - http:
          path: event
          method: post
 